version: "3"

services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - .:/var/www/vinyl-crawler/
    ports:
      - "7001:80"
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www/vinyl-crawler/
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "7002:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: vinyl_crawler
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
